params:
  training_experiment: baselines.train_kmeans
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: ExathlonDataset
training_param_updates:
  dataset:
    name: ExathlonDataset
  training:
    epochs: 1
    batch_size: 1024
training_param_grid:
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
          step_size:
            - 1
            - 5
            - 10
detector_param_grid:
  detector_params:
    k:
      - 10
      - 50
      - 100
