params:
  training_experiment: reconstruction.train_timesnet
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 10
training_param_grid:
  model_params:
    d_model:
      - 64
    e_layers:
      - 2
    d_ff:
      - 64
    dropout:
      - 0.0
      - 0.1
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 100
